import {
	APP_DEFAULT_PORT,
	DB_DEFAULT_DIALECT,
	DB_DEFAULT_PORT,
	DEVELOPMENT,
	LOCALHOST,
	MIGRATIONS,
	REDIS_DEFAULT_PORT,
	SOCKET_AGENT_DEFAULT_PATH,
	SOCKET_AGENT_DEFAULT_PORT,
	SOCKET_CUSTOMER_DEFAULT_PATH,
	SOCKET_CUSTOMER_DEFAULT_PORT,
} from "./config-values.const";
import {
	ACCESS_TOKEN_EXPIRY,
	APP_HOST,
	APP_PORT,
	CRYPT_AUTH_TAG_BYTE_LEN,
	CRYPT_BLOCK_CIPHER,
	CRYPT_ENCRYPTION_KEY_BYTE_LENGTH,
	CRYPT_HASH_SALT_ITERATIONS,
	CRYPT_INITIALIZATION_VECTOR_BYTE_LEN,
	CRYPT_SALT_BYTE_LEN,
	CRYPT_SALT_ITERATIONS,
	CRYPT_SALT_SCHEME,
	CUSTOMER_TOKEN_EXPIRY,
	DB_DIALECT,
	DB_GENERATOR,
	DB_HOST,
	DB_PORT,
	REDIS_HOST,
	REDIS_PORT,
	REFRESH_TOKEN_EXPIRY,
	SOCKET_AGENT_PATH,
	SOCKET_AGENT_PORT,
	SOCKET_CUSTOMER_PATH,
	SOCKET_CUSTOMER_PORT,
} from "./config.const";

export const ConfigDefaultsConst = {
	Environment: DEVELOPMENT,

	Token: {
		[ACCESS_TOKEN_EXPIRY]: "5m",
		[REFRESH_TOKEN_EXPIRY]: "24hr",
		[CUSTOMER_TOKEN_EXPIRY]: "24hr",
	},

	Database: {
		[DB_HOST]: LOCALHOST,
		[DB_DIALECT]: DB_DEFAULT_DIALECT,
		[DB_PORT]: DB_DEFAULT_PORT,
		[DB_GENERATOR]: MIGRATIONS,
	},

	Redis: {
		[REDIS_HOST]: LOCALHOST,
		[REDIS_PORT]: REDIS_DEFAULT_PORT,
	},

	Crypt: {
		[CRYPT_BLOCK_CIPHER]: "aes-256-gcm",
		[CRYPT_AUTH_TAG_BYTE_LEN]: 16,
		[CRYPT_INITIALIZATION_VECTOR_BYTE_LEN]: 16,
		[CRYPT_ENCRYPTION_KEY_BYTE_LENGTH]: 32,
		[CRYPT_SALT_BYTE_LEN]: 64,
		[CRYPT_SALT_ITERATIONS]: 100000,
		[CRYPT_SALT_SCHEME]: "sha512",
		[CRYPT_HASH_SALT_ITERATIONS]: 10,
	},

	Socket: {
		[SOCKET_AGENT_PORT]: SOCKET_AGENT_DEFAULT_PORT,
		[SOCKET_AGENT_PATH]: SOCKET_AGENT_DEFAULT_PATH,
		[SOCKET_CUSTOMER_PORT]: SOCKET_CUSTOMER_DEFAULT_PORT,
		[SOCKET_CUSTOMER_PATH]: SOCKET_CUSTOMER_DEFAULT_PATH,
	},

	App: {
		[APP_HOST]: LOCALHOST,
		[APP_PORT]: APP_DEFAULT_PORT,
	},
};
