export const NODE_ENV = "NODE_ENV";

export const ACCESS_TOKEN_SECRET = "ACCESS_TOKEN_SECRET";
export const REFRESH_TOKEN_SECRET = "REFRESH_TOKEN_SECRET";
export const ACCESS_TOKEN_EXPIRY = "ACCESS_TOKEN_EXPIRY";
export const REFRESH_TOKEN_EXPIRY = "REFRESH_TOKEN_EXPIRY";

export const DB_USERNAME = "DB_USERNAME";
export const DB_PASSWORD = "DB_PASSWORD";
export const DB_DATABASE = "DB_DATABASE";
export const DB_HOST = "DB_HOST";
export const DB_DIALECT = "DB_DIALECT";
export const DB_PORT = "DB_PORT";
export const DB_SCHEMA = "DB_SCHEMA";
export const DB_GENERATOR = "DB_GENERATOR";

export const REDIS_HOST = "REDIS_HOST";
export const REDIS_PORT = "REDIS_PORT";
export const REDIS_USERNAME = "REDIS_USERNAME";
export const REDIS_PASSWORD = "REDIS_PASSWORD";

export const CRYPT_APP_KEY = "CRYPT_APP_KEY";
export const CRYPT_BLOCK_CIPHER = "CRYPT_BLOCK_CIPHER";
export const CRYPT_AUTH_TAG_BYTE_LEN = "CRYPT_AUTH_TAG_BYTE_LEN";
export const CRYPT_INITIALIZATION_VECTOR_BYTE_LEN = "CRYPT_INITIALIZATION_VECTOR_BYTE_LEN";
export const CRYPT_ENCRYPTION_KEY_BYTE_LENGTH = "CRYPT_ENCRYPTION_KEY_BYTE_LENGTH";
export const CRYPT_SALT_BYTE_LEN = "CRYPT_SALT_BYTE_LEN";
export const CRYPT_SALT_ITERATIONS = "CRYPT_SALT_ITERATIONS";
export const CRYPT_SALT_SCHEME = "CRYPT_SALT_SCHEME";
export const CRYPT_HASH_SALT_ITERATIONS = "CRYPT_HASH_SALT_ITERATIONS";

export const APP_HOST = "APP_HOST";
export const APP_PORT = "APP_PORT";
export const APP_NAME = "APP_NAME";
export const APP_VERSION = "APP_VERSION";
